### ISSUE TITLE
Error at Deployment

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [tulir/tgfilestream#8]
(venv) ubuntu@ip-172-26-8-181:~/tgfilestream$ python3 -m tgfilestream
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/tgfilestream/tgfilestream/__main__.py", line 22, in <module>
    from .telegram import client, transfer
  File "/home/ubuntu/tgfilestream/tgfilestream/telegram.py", line 20, in <module>
    from .paralleltransfer import ParallelTransferrer
  File "/home/ubuntu/tgfilestream/tgfilestream/paralleltransfer.py", line 17, in <module>
    from contextlib import asynccontextmanager
ImportError: cannot import name 'asynccontextmanager'

**Comment by tulir** [comment]
Update to Python 3.7
